inspire-eu-validation/ets-repository

generic/ets-generic-bsxets.xq
inspire/data-hy/hy-p-as/ets-hy-p-as-bsxets.xml
inspire/data-ps/ps-as/ets-ps-as-bsxets.xml
inspire/data-ps/ps-gml/ets-ps-gml-bsxets.xml
inspire/data/schemas/ets-schemas-bsxets.xml
inspire/include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52-ettb.xml
inspire/inspire-bsxets.xq
inspire/inspire-md-bsxets.xq

Only commit once the new version of the GmlGeoX JAR has been published and the deployed etf-bsxds has been changed to the new schema version

Schema and ggeo changes

---

data-encoding/inspire-gml/ets-inspire-gml-bsxets.xml

Ref interactive-instruments/etf-webapp-docker#6

TR.validationError message reference corrected

---

.gitignore
docs/User_manual/Annex_I_Data_Set.adoc
docs/User_manual/Annex_I_Data_Set.html
docs/User_manual/Download_Services.adoc
docs/User_manual/Download_Services.html
docs/User_manual/Metadata.adoc
docs/User_manual/Metadata.html
docs/User_manual/index.adoc
docs/User_manual/index.html

http://inspire-eu-validation.github.io/ets-repository/User_manual/index.html

Documentation

---

metadata/iso/ets-md-iso-bsxets.xml
testquery-md.xq
testquery-noggeo.xq
testquery.xq

* change handling of TR.unknownResourceType in md-iso.d.3
Closes #62
* access the INSPIRE registry using https
* treat http and https URIs as equivalent
Closes #64

Multiple fixes

---

data/schemas/ets-schemas-bsxets.xml

The object element was not included in the path expressions.
Resolves #67

Fix error in path

---

metadata/iso/ets-md-iso-bsxets.xml

iso-md.c.2: allow all language codes

---

testquery-noggeo.xq
testquery.xq

A nodeset was used in one place where only a single node is allowed in
a functx function.

Fix issue in bugfix for #64

---

metadata/iso/ets-md-iso-bsxets.xml

Forgot to increase version date and number in #77

Update version metadata

---

data-ps/ps-ia/ets-ps-ia-bsxets.xml
data/schemas/ets-schemas-bsxets.xml

Also add check for properties in first level data types to the GML
model checks.
resolves #109

Add check for existence of xlink:href

---

.github/ISSUE_TEMPLATE.md
service/ds-atom-pre-defined-soapui-project.xml
testquery.xq

Please note: the changes require the new version 1.2.0 of GmlGeoX which is packaged with the [third release candidate (2.0.0-rc.3](https://github.com/interactive-instruments/etf-webapp/releases/tag/2.0.0-rc.3)) of the ETF webapp

3D validation + issue template

---

data-tn/tn-ia/ets-tn-ia-bsxets.xml

Changes expected feature types of the MarkerPost.route property

Fix Issue 112

---

data/interoperability-metadata/ets-md-iop-bsxets.xml

@michellutz 
Modifications in ETS for the issue #30.

Helpdesk - Issue #30

---

data/interoperability-metadata/ets-md-iop-bsxets.xml

The XPath of 'Coordinate Reference System' and 'Spatial Representation Type' is relaxed.

Modifications in the ETS to solve the issue #45

---

data/schemas/ets-schemas-bsxets.xml

The test will pass validation when the element has an attribute 'indeterminatePosition' with one of the following values:
'unknown', 'now', 'before' or 'after'.
Note: The test will be correct even if the element has an empty value.

Modifications in the ETS to solve the issue 46

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Now the ETF displays the correct message.

Modifications on the ETS for issue #70

---

metadata/2.0/common/ets-md-common-bsxets.xml

Message that shows the title of the Thesaurus Name.

Modifications on the ETS for issue 70

---

data/interoperability-metadata/ets-md-iop-bsxets.xml
metadata/1.3/iso/ets-md-iso-bsxets.xml
metadata/1.3/xml/ets-md-xml-bsxets.xml
metadata/2.0/common/ets-md-common-bsxets.xml

We updated the links from tests and fixed the issue 52

Bugfix 1.1

---

service/dis-csw-core-soapui-project.xml

Fixed issue 101

---

metadata/1.3/xml/ets-md-xml-bsxets.xml

Metadata 1.3 XML Schema Validation fixed to: https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd

Xml validation metadata 1.3

---

include-metadata/TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml

Correct several typos in error messages displayed to the user.

Correct typos

---

metadata/2.0/common/ets-md-common-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-isdss-bsxets.xml
metadata/2.0/sds/ets-md-sds-bsxets.xml
metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml

MD TG 2.0 remove codelist validation except in C.5 'Language Code' and 1.6 'Resource Language'

MD TG 2.0 remove codelist validation

---

metadata/2.0/common/ets-md-common-bsxets.xml

Allowed to insert more than one Company Mail
[#148](https://github.com/inspire-eu-validation/community/issues/148)

Fix issue 148

---

metadata/2.0/common/ets-md-common-bsxets.xml

Reverts inspire-eu-validation/ets-repository#362

Revert "Fix issue 148"

---

metadata/2.0/sds/ets-md-sds-bsxets.xml

Relax test for md sds 3.1: Resource Type
Corresponding issue: [#100](https://github.com/inspire-eu-validation/community/issues/100)

Relax test on issue 100

---

metadata/2.0/sds/ets-md-sds-bsxets.xml

Relax test for md sds 3.1: Resource Type

Fix error on issue 100

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/sds/ets-md-sds-bsxets.xml

Stronger test for md sds 3.1 and md sds 3.8
Corresponding community issue: [#96](https://github.com/inspire-eu-validation/community/issues/96)

Fix issue 96

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Relax codeListValue validation from Metadata 2.0 C.6
Corresponding community issue: [#178](https://github.com/inspire-eu-validation/community/issues/178)

Update test MD 2.0 C.6

---

metadata/2.0/sds/ets-md-sdsinvocable-bsxets.xml

Committer: Daniel Navarro Cueto <daniel.navarro@geograma.com>
Fixed issue https://github.com/inspire-eu-validation/community/issues/183

Fixed issue 183. Modified harmonished for harmonised

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/sds/ets-md-sds-bsxets.xml

Update test for MD 2.0 Requirement 3.4
Corresponding Issue: [#181](https://github.com/inspire-eu-validation/community/issues/181)

Update test for issue 181

---

metadata/2.0/sds/ets-md-sds-bsxets.xml

Fix issue [189](https://github.com/inspire-eu-validation/community/issues/189)

Fixed lower case check in 3.1 and 3.8 requirements

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Update test for MD 2.0 C.14
Corresponding issue: [#188](https://github.com/inspire-eu-validation/community/issues/188)

Fix issue 188

---

metadata/2.0/common/ets-md-common-bsxets.xml

[Fixed issue 202](https://github.com/inspire-eu-validation/community/issues/202)

Deleted date regex validation in C.12 and C.13

---

metadata/2.0/common/ets-md-common-bsxets.xml

Updated issue [202](https://github.com/inspire-eu-validation/community/issues/202)

Fix temporal reference datetime regexp

---

metadata/1.3/xml/ets-md-xml-bsxets.xml

Corresponding issue: [161](https://github.com/inspire-eu-validation/community/issues/161)
Update test for MD 1.3 XML A.1

Fix issue 161

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Relax test for MD 2.0 C.18 
Corresponding issue [194](https://github.com/inspire-eu-validation/community/issues/194)

Relax test for MD 2.0 C18

---

data/schemas/ets-schemas-bsxets.xml

Update test for issue [206](https://github.com/inspire-eu-validation/community/issues/206)

Fix test gmlas.c.1

---

metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml

Fixed issue [228](https://github.com/inspire-eu-validation/community/issues/228).

Fixed enumeration retrieval

---

metadata/2.0/common/ets-md-common-bsxets.xml

Relax test from MD2.0 C.5
Corresponding issue: [239](https://github.com/inspire-eu-validation/community/issues/239)

Relax test from MD2.0 C.5

---

metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml

Update test from MD 2.0 1.6

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/1.3/iso/ets-md-iso-bsxets.xml

Fixed issue https://github.com/inspire-eu-validation/community/issues/260

Fixed issue 260

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-monitoring-bsxets.xml

Added new ETS for Metadata 2.0 for Monitoring https://github.com/inspire-eu-validation/community/issues/272

Monitoring metadata

---

metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml

Fix issue https://github.com/inspire-eu-validation/community/issues/318

Fix duplicate dataset UID

---

data-am/am-as/ets-am-as-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Reverts inspire-eu-validation/ets-repository#493

Revert "Data am staging"

---

data-am/am-as/ets-am-as-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Reverts inspire-eu-validation/ets-repository#499

Revert "Revert "Data am staging""

---

data-nz/nz-as/ets-nz-as-bsxets.xml
data-nz/nz-dc/ets-nz-dc-bsxets.xml
data-nz/nz-gml/ets-nz-gml-bsxets.xml
data-nz/nz-ia/ets-nz-ia-bsxets.xml
data-nz/nz-rs/ets-nz-rs-bsxets.xml
include-metadata/Tag-EID00d4d7af-152b-4644-aeda-c8983df4535f.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
testquery-noggeo.xq
testquery.xq
v4_uuids.txt

Reverts inspire-eu-validation/ets-repository#498

Revert "Revert "Data nz staging""

---

data-sd/sd-as/ets-sd-as-bsxets.xml
data-sd/sd-dc/ets-sd-dc-bsxets.xml
data-sd/sd-gml/ets-sd-gml-bsxets.xml
data-sd/sd-ia/ets-sd-ia-bsxets.xml
data-sd/sd-rs/ets-sd-rs-bsxets.xml
include-metadata/Tag-EIDce23680b-d081-400e-93b0-030ed193b78e.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
testquery-noggeo.xq
testquery.xq
v4_uuids.txt

Reverts inspire-eu-validation/ets-repository#497

Revert "Revert "Data sd staging""

---

metadata/2.0/common/ets-md-common-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml

More information in the issue [#373](https://github.com/inspire-eu-validation/community/issues/373)

Fixed different System Errors on MD 2.0

---

data-ge/ge-core-as/ets-ge-core-as-bsxets.xml
data-ge/ge-gp-as/ets-ge-gp-as-bsxets.xml
data-ge/ge-hg-as/ets-ge-hg-as-bsxets.xml
data-ge/ge-ia/ets-ge-ia-bsxets.xml

Geology paths fixed due to wrongmultiplicity messages

Data ge issue 518

---

metadata/2.0/sds/ets-md-sds-bsxets.xml

Corresponding issue: [#419](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/419)

Updated CharacterString validation dor MD 2.0 3.4

---

data-sd/sd-as/ets-sd-as-bsxets.xml
data-sd/sd-ia/ets-sd-ia-bsxets.xml

Corresponding issue: [#518](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/518)

Species distribution paths and wrongMultiplicity messages fixed

---

data-hb/hb-as/ets-hb-as-bsxets.xml

hb-as.a.4 wrong multiplicity fix

Issue 526 

---

service/ds-wfs-direct-soapui-project.xml

Modified EID dependency on WFS Direct for OGC WFS 2.0

Modified EID dependency on WFS Direct for OGC WFS 2.0

---

data-lu/lu-gml/ets-lu-gml-bsxets.xml

Corresponding issue : [#440](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/440)

Fixed prefixes on lu-gml

---

data-hb/hb-as/ets-hb-as-bsxets.xml

Corresponding issue: [#526](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/526)

hb-as.a.4 paths fixed

---

service/ds-wcs-core-soapui-project.xml

Corresponding issue: [#532](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/532)

Parsed 'lang' to String to avoid type error

---

service/ds-wfs-direct-soapui-project.xml
service/ds-wfs-pre-defined-soapui-project.xml

Corresponding issue: [#576](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/576)

Added missing semicolons to WFS

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#572](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/572)

Added missing ';' to media-type test & Update URL to point against atom URL

---

service/vs-wms-soapui-project.xml

Corresponding issue: [#587](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/587)

Updated wrong variable

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#601](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/601)

noDateTypeForSpecification message typo fixed

---

data/data-consistency/ets-data-consistency-bsxets.xml

Corresponding issue: [#612](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/612)

Created for loop to different features.

---

data-so/so-as/ets-so-as-bsxets.xml

Corresponding issue: [#643](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/643)

Created loop to avoid problems defining messages

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#642](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642)

Update wrong rel search on ATOM

---

data-su/su-gml/ets-su-gml-bsxets.xml

Corresponding issue: [#646](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/646)

Update StatisticalTesselation to StatisticalTessellation

---

data-mr/mr-as/ets-mr-as-bsxets.xml

Corresponding issue [#649](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/649)

Update mr-as.b.1: specification test

---

metadata/2.0/sds/ets-md-sds-bsxets.xml
testquery-md.xq

Corresponding issue: [#515](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/515)

Add log to check received uri

---

testquery-md.xq

Corresponding issue: [#515](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/515)

Add log to check redirections

---

metadata/2.0/sds/ets-md-sds-bsxets.xml
testquery-md.xq

Corresponding issue: [#515](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/515)

Add logs to retrieve more information about the random-fails 

---

data-so/so-ia/ets-so-ia-bsxets.xml

Corresponding issue: [#659](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/659)

Removed multiplicity check for so:soilDerivedObjectObservation

---

service/vs-wms-soapui-project.xml

Close of issue [#584](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/584). Changes are no more needed.

Revert "Removed serviceException count"

---

service/ds-wfs-pre-defined-soapui-project.xml

Corresponding issue: [#638](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/638)

Check operatesOn/@xLink:href instead of operatesOn/@uuidref

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

MD 2.0 Conformance Class 2.C: IACS

---

metadata/2.0/common/ets-md-common-bsxets.xml

Issue detected during monitoring. No issue associated.

Add 'nor' language to c.5

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

MD 2.0 2C IACS

---

data/data-consistency/ets-data-consistency-bsxets.xml

Corresponding issue: [#612](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/612)

Accepted date and dateTime

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
service/vs-wms-soapui-project.xml

Corresponding issue: [#626](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/626)

BU.Building.default option style added

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#633](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/633)

Update emptyName message

---

service/ds-wfs-direct-soapui-project.xml

Corresponding issue: [#565](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/565)

etf.dependency.ids value updated

---

data-ge/ge-ia/ets-ge-ia-bsxets.xml

Corresponding issue: [#625](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/625)

ge-ia.b.2 and ge-ia.b.3 missing element and wrong multiplicity removed

---

metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#688](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/688)

C.18 otherConstraints Anchor condition updated

---

data-lc/lc-as/ets-lc-as-bsxets.xml

Corresponding issue: [#704](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/704)

lc-as.a.1 updated

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

IACS check in the document added

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml

Corresponding issue: [#567](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/567)

common-req C.5 and datasets-and-series 1.6 codelists updated

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

All IACS codelist messages are displayed

---

data-bu/bu-3d-as/ets-bu-3d-as-bsxets.xml

Corresponding issue: [#712](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/712)

bu-3d-as.a.3 and bu-3d-as.a.4 fixed

---

metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#327](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/327)

Add nor language to c.5

---

data-ge/ge-ia/ets-ge-ia-bsxets.xml

Corresponding issue: [#625](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/625)

ge-ia.b.2 and ge-ia.b.3 missing element and wrong multiplicity conditions removed

---

data-bu/bu-3d-as/ets-bu-3d-as-bsxets.xml

Corresponding issue: [#712](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/712)

bu-3d-as.a.3 and bu-3d-as.a.4 checks each buildingpart of bu-base:parts

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

INSPIRE data sets and data set series metadata for IACS 

---

metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#706](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/706)

common req C.5 ice language code added

---

data-er/er-gml/ets-er-gml-bsxets.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#729](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/729)

Conformance class description typo fixed

---

data-am/am-gml/ets-am-gml-bsxets.xml
testquery-noggeo.xq
testquery.xq
v4_uuids.txt

Pending to assign to an issue.

am official schema validation added

---

data-am/am-gml/ets-am-gml-bsxets.xml
data/schemas/ets-schemas-bsxets.xml

gmlas.b and am-gml.b.1 labels and description updated

---

data-am/am-gml/ets-am-gml-bsxets.xml

am-gml.b and am-gml.b.1 descriptions updated

---

data-am/am-gml/ets-am-gml-bsxets.xml

am-gml.b and am-gml.b.1 description typos fixed

---

include-metadata/TranslationTemplateBundle-EIDfa68eb83-a25a-4009-84dd-036de4539c93.xml

Corresponding issue: [#618](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/618)

invalidLegendFormat message updated

---

data-ge/ge-gml/ets-ge-gml-bsxets.xml
data-pf/pf-gml/ets-pf-gml-bsxets.xml
data-so/so-gml/ets-so-gml-bsxets.xml
v4_uuids.txt

ge, pf and so official schema validation added

---

data-am/am-gml/ets-am-gml-bsxets.xml
data-ge/ge-gml/ets-ge-gml-bsxets.xml
data-mr/mr-gml/ets-mr-gml-bsxets.xml
data-nz/nz-gml/ets-nz-gml-bsxets.xml
data-of/of-gml/ets-of-gml-bsxets.xml
data-pf/pf-gml/ets-pf-gml-bsxets.xml
data-so/so-gml/ets-so-gml-bsxets.xml
testquery-noggeo.xq
testquery.xq
v4_uuids.txt

mr, nz and of official schema validation added

---

data-us/us-gml/ets-us-gml-bsxets.xml
v4_uuids.txt

us official schema validation added

---

data-pf/pf-gml/ets-pf-gml-bsxets.xml

Corresponding issue: [#747](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/747)

pf-gml typo fixed

---

data-cp/cp-rs/ets-cp-rs-bsxets.xml
data/reference-systems/ets-reference-systems-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-isdss-bsxets.xml
metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml

Corresponding issue: [#742](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/742)

5621, 9389 and 9390 EPSG codes added

---

data-cp/cp-gml/ets-cp-gml-bsxets.xml
data-hb/hb-gml/ets-hb-gml-bsxets.xml
data-hh/hh-gml/ets-hh-gml-bsxets.xml
data-su/su-gml/ets-su-gml-bsxets.xml
v4_uuids.txt

cp, hb, hh and su official schema validation added

---

data-su/su-vector-as/ets-su-vector-as-bsxets.xml

Corresponding issue: [#714](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/714)

su-vector-as.b.1 and su-vector-as.b.2 updated

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#751](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/751)

OpenSearch description updated

---

data-pd/pd-gml/ets-pd-gml-bsxets.xml
data-tn/tn-gml/ets-tn-gml-bsxets.xml
v4_uuids.txt

pd and tn official schema validation added

---

data-au/au-gml/ets-au-gml-bsxets.xml
data-ef/ef-gml/ets-ef-gml-bsxets.xml
data-er/er-gml/ets-er-gml-bsxets.xml
v4_uuids.txt

au, ef and er official schema validation added

---

data-gn/gn-gml/ets-gn-gml-bsxets.xml
data-lc/lc-gml/ets-lc-gml-bsxets.xml
data-sd/sd-gml/ets-sd-gml-bsxets.xml
v4_uuids.txt

gn, lc and sd schema validation added

---

data-hy/hy-gml/ets-hy-gml-bsxets.xml
data-lu/lu-gml/ets-lu-gml-bsxets.xml
data-sr/sr-gml/ets-sr-gml-bsxets.xml
v4_uuids.txt

hy, lu and sr schema validation added

---

data-sr/sr-gml/ets-sr-gml-bsxets.xml

 sr-gml.b.1 link typo fixed

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#727](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/727)

gco:CharacterString changed to language list values

---

data-ad/ad-gml/ets-ad-gml-bsxets.xml
data-br/br-gml/ets-br-gml-bsxets.xml
data-oi/oi-gml/ets-oi-gml-bsxets.xml
data-ps/ps-gml/ets-ps-gml-bsxets.xml
v4_uuids.txt

ad, br, oi and ps official schema validation added

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#770](https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/770)

INSPIRE data sets and data set series metadata for IACS multilanguage

---

include-metadata/TranslationTemplateBundle-EID67b37079-9ac5-4641-9476-9a646a18b6ce.xml
service/ds-wcs-core-soapui-project.xml

Corresponding issue: [#683](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/683)

at03 check changed to manual and message updated

---

data-sd/sd-gml/ets-sd-gml-bsxets.xml

Corresponding issue: [#798](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/798)

sd:SpeciesDistributionUnit added in sd-gml.a.1

---

data-af/af-gml/ets-af-gml-bsxets.xml

Corresponding issue: [#809](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/809)

af:Site added in af-gml.a.1

---

inspire-bsxets.xq
inspire-noggeo-bsxets.xq

Corresponding issue: [#788](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/788)

wfs:member additionalObjects path added

---

data-au/au-dc/ets-au-dc-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#788](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/788)

au-dc.f.1 manual check added

---

data-bu/bu-3d-as/specific-schemas/ets-bu-gml-bsxets.xml
data-bu/bu-gml/ets-bu-gml-bsxets.xml

Corresponding issue: [#816](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/816)

 BuildingPart added in bu-gml-a.1

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#824](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/824)

C15 codeListValue and error message updated

---

data-sr/sr-as/ets-sr-as-bsxets.xml

Corresponding issue: [#830](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/830)

sr-as.b.3 Polygon, PolyhedralSurface and TriangulatedSurface added

---

metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml
service/vs-wms-soapui-project.xml
service/vs-wmts-soapui-project.xml

Corresponding issue: [#844](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/844)

wms and wmts description links updated

---

data-bu/bu-3d-as/specific-schemas/ets-bu-gml-bsxets.xml
data-bu/bu-gml/ets-bu-gml-bsxets.xml

Corresponding issue: [#816](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/816)

BuildingPart added in bu-gml-a.1

---

include-metadata/TranslationTemplateBundle-EIDb02cc4ae-60e1-47a5-8e5a-7f9769ffd113.xml
include-metadata/TranslationTemplateBundle-EIDfa68eb83-a25a-4009-84dd-036de4539c93.xml
service/vs-wms-soapui-project.xml
service/vs-wmts-soapui-project.xml

Corresponding issue: [#822](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/822)

at39bis layer title manual check added

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
service/vs-wms-soapui-project.xml

Corresponding issue: [#854](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/854)

noAccessText error message updated

---

data-hy/hy-n-as/ets-hy-n-as-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#852](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/852)

hy-n-as.b.1 geometry manual check added

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#873](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/873)

Topic category validation fixed

---

data-nz/nz-ia/ets-nz-ia-bsxets.xml

Corresponding issue: [#883](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/883)

nz-ia.a.2 SpecificExposedElementTypeValue path fix

---

data-ad/ad-ia/ets-ad-ia-bsxets.xml
data-au/au-ia/ets-au-ia-bsxets.xml
data-cp/cp-ia/ets-cp-ia-bsxets.xml
data-hy/hy-ia/ets-hy-ia-bsxets.xml
data-tn/tn-ia/ets-tn-ia-bsxets.xml

Corresponding issue: [#559](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/559)

ad, au, cp, hy and tn http redirections fixed

---

service/ds-wfs-direct-soapui-project.xml

Corresponding issue: [#900](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/900)

WFS Direct dependency updated

---

include-metadata/TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml
service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#661](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/661)

application/atom+xml and text/xml added as valid types

---

data-bu/bu-3d-as/specific-schemas/ets-bu-as-bsxets.xml
data-bu/bu-as/ets-bu-as-bsxets.xml

Corresponding issue: [#898](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/898)

bu-as.a.11 currentUse valid_href path fixed

---

data-tn/tn-as/ets-tn-as-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#849](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/849)

tn-as.c.1 geometry manual check added

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#928](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/928)

Keyword GEMET value displays all error messages

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#928](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/928)

Common Agricultural Policy typos fixed

---

inspire-bsxets.xq
inspire-noggeo-bsxets.xq

Corresponding issue: [#930](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/930)

new features paths added in inspire and inspire-noggeo

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#928](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/928)

Keyword GEMET changes reverted

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/sds/ets-md-sds-bsxets.xml

Corresponding issue: [#141](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/141)

md sds 3.6 Coupled Resource manual check added

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#927](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/927)

Citation Date also allows gco:DateTime

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#928](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/928)

Keyword split into INSPIRE data theme and GEMET

---

include-metadata/TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml
service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#819](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819)

TG Req 43 and TG Req 44 updated

---

data-tn/tn-as/ets-tn-as-bsxets.xml
include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml

Corresponding issue: [#113](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/113)

tn-as.c.1 significantPoint exception added for air TransportNode

---

data-am/am-as/ets-am-as-bsxets.xml

Corresponding issue: [#943](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/943)

am-as.b.2 competentAuthority xsi:nil condition added

---

data-hh/hh-as/ets-hh-as-bsxets.xml
data-hh/hh-gml/ets-hh-gml-bsxets.xml
data-hh/hh-ia/ets-hh-ia-bsxets.xml

Corresponding issue: [#1046](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1046)

hh-gml updated, hh-as.b.3 and hh-ia.a.8 added

---

data-su/su-as/ets-su-as-bsxets.xml
data-su/su-grid-as/ets-su-grid-as-bsxets.xml

Corresponding issue: [#1049](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1049)

su-as-a.2 and su-grid-as.a.5 descriptions updated

---

data-hy/hy-p-as/ets-hy-p-as-bsxets.xml

Corresponding issue: [#1052](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1052)

hy-p-as.d.1 added

---

data-hh/hh-gml/ets-hh-gml-bsxets.xml
data-hh/hh-ia/ets-hh-ia-bsxets.xml

Corresponding issue: [#1046](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1046)

hh-ia.a.2 hh-ia.a.8 and hh-ia.a.9 added

---

data/reference-systems/ets-reference-systems-bsxets.xml
metadata/2.0/datasets-and-series/ets-md-isdss-bsxets.xml
metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml

Corresponding issue: [#1066](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1066)

epsg now is retrieved from inspire link in rs, CC2 and CC6

---

data-sd/sd-ia/ets-sd-ia-bsxets.xml

Corresponding issue: [#1028](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1028)

sd-ia.a.2 xsi:nil condition added

---

data-hh/hh-as/ets-hh-as-bsxets.xml
data-hh/hh-gml/ets-hh-gml-bsxets.xml
data-hh/hh-ia/ets-hh-ia-bsxets.xml

Corresponding issue: [#1046](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1046)

hh-gml updated, hh-as.b.3, hh-ia.a.2, hh-ia.a.8 and hh-ia.a.9 added

---

data-su/su-ia/ets-su-ia-bsxets.xml

Corresponding issue: [#1048](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1048)

su-ia.a.2 added

---

data-lc/lc-ia/ets-lc-ia-bsxets.xml

Corresponding issue: [#1050](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1050)

lc-ia.b.2 added

---

include-metadata/TranslationTemplateBundle-EIDfa68eb83-a25a-4009-84dd-036de4539c93.xml
metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml
service/vs-wms-soapui-project.xml

at09 to at29 removed due to simplification

at06-getcapabilities-view-service-metadata added

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#1085](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1085)

TG Req 42 Get Opensearch condition fixed

---

service/vs-wms-soapui-project.xml

Corresponding issue [#1099](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1099)

at06 content-type condition removed

---

include-metadata/TranslationTemplateBundle-EIDfa68eb83-a25a-4009-84dd-036de4539c93.xml
service/vs-wms-soapui-project.xml

Corresponding issues: [#1098](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1098) [#1099](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1099)

Support to data-service linking simplification for WMS included 

---

include-metadata/TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml
service/ds-atom-pre-defined-soapui-project.xml
service/ds-wfs-pre-defined-soapui-project.xml

Corresponding issue: [#1116](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1116)

WFS Predefined and Predefined Atom data-service linking simplification

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#1115](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1115)

metadata IACS keyword GEMET anchor valid url added

---

metadata/2.0/datasets-and-series/ets-md-iacs-bsxets.xml

Corresponding issue: [#1115](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1115)

keyword GEMET anchor valid url updated

---

data-ef/ef-ia/ets-ef-ia-bsxets.xml
testquery-noggeo.xq

Corresponding issue: [#1128](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1128)

ef-ia.b.16 procedure path exception added

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#377](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/377)

Predefined Atom - TG Req 27 updated

---

service/ds-atom-pre-defined-soapui-project.xml
service/ds-wfs-pre-defined-soapui-project.xml

Corresponding issue: [#124](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/124)

predefined atom and predefined wfs namespace are now optional

---

metadata/2.0/common/ets-md-common-bsxets.xml

Corresponding issue: [#1135](8https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1135)

md common C13 error message fixed

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/datasets-and-series/ets-md-mrl-bsxets.xml

Corresponding issue: [#1136](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1136)

Download service linking wfs check updated

---

metadata/2.0/sds/ets-md-ns-monitoring-bsxets.xml

new Conformance Class 4b: INSPIRE Network Services metadata for Monitoring related to the issue 251 https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/251

new Conformance Class 4b: INSPIRE Network Services metadata for Monitoring

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [1179](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1179)

Predefined Atom TG Req 43 mimetype condition updated

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#124](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/124)

Predefined Atom TG Req 43 condition fixed

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#124](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/124)

TG Req 43 and 44 namespace is optional.

---

service/ds-atom-pre-defined-soapui-project.xml
service/ds-wfs-pre-defined-soapui-project.xml

Corresponding issue: [#124](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/124)

Predefined Atom and Predefined WFS namespaces are now optional

---

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
metadata/2.0/sds/ets-md-ns-monitoring-bsxets.xml

We will include new CC4b with its related error message to next branch

new CC4b test to next branch

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#1210](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1210)

TG Req 28 url condition fixed

---

service/ds-atom-pre-defined-soapui-project.xml

Corresponding issue: [#1218](https://public.epsilon-italia.it/atom/sample_issue-1218/atom.service-feed.TOP.en.xml)

Atom TG Requirement 27 alternate link path fixed
