data-ps/ps-ia/ets-ps-ia-bsxets.xml, data/information-accessibility/ets-information-accessibility-bsxets.xml, metadata/iso/ets-md-iso-bsxets.xml
\d{3} was matching all cases where a sequence of 3 digits was included
(in this case in the media type), not just the status codes
=> distinction of resource access results to weak

metadata/iso/ets-md-iso-bsxets.xml
For metadata elements that may be multilingual text, only use the first
language (unless the test is about the multilingual values) and ignore
the second element (`PT_FreeText`).
Resolves #76
=> Elements with multilingual text

metadata/iso/ets-md-iso-bsxets.xml
The check for the text value of dateType element is removed. The assertion should only check that the codeListValue attribute is "publication".
Issue: #180
=> Modifications in the ETS to solve the issue #180

data/interoperability-metadata/ets-md-iop-bsxets.xml
Call to the https secure urls instead of the http to avoid the redirection.
ets-repository issue: #189 
community issue: inspire-eu-validation/community#5
=> Modifications in the ETS to solve the issue #189

metadata/iso/ets-md-iso-bsxets.xml
The validations have been divided in two main blocks of code. In a first step the ETS validates that exists at least one url that is a valid service (WFS, WMS, WCS, SOS or Atom). In a second step, if exist at least one url that fulfils this requirement there will be no 'TR.unknownXMLResource' errors. If there are, the other warning(s) will be shown.
=> Modifications in the ETS to solve the issue #117

data/schemas/ets-schemas-bsxets.xml
The test will pass validation when the element has an attribute 'indeterminatePosition' with one of the following values:
- unknown
- now
=> Modifications in the ETS to solve the issue 46

metadata/2.0/sds/ets-md-sds-bsxets.xml
There was an error that blocks the execution of MD 2.0 CC3 tests.
Corresponding issue: [#154](https://github.com/inspire-eu-validation/community/issues/154)
=> Fixed error 154

metadata/1.3/xml/ets-md-xml-bsxets.xml
Add support for new schemaLocation links on MD 1.3
Corresponding community issue: [#161](https://github.com/inspire-eu-validation/community/issues/161)
=> fix MD 1.3

metadata/1.3/xml/ets-md-xml-bsxets.xml
Add support for new schemaLocation links on MD 1.3
Corresponding community issue: [#161](https://github.com/inspire-eu-validation/community/issues/161)
=> Fixed MD 1.3 for issue 161

testquery-noggeo.xq
Update testquery-noggeo from https to http
Corresponding community issue: [#140](https://github.com/inspire-eu-validation/community/issues/140)
=> From https to http

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml, metadata/2.0/common/ets-md-common-bsxets.xml
Improve unspecific error message on MD 2.0 Requirement C.6
Corresponding community issue: [#178](https://github.com/inspire-eu-validation/community/issues/178)
=> Update wrong error message

metadata/2.0/common/ets-md-common-bsxets.xml
Corresponding issue: [#480](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/480)
=> Relaxed error C.14 to allow before and after

include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml
Corresponding issue: [#601](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/601)
=> noDateTypeForSpecification message typo fixed

data-am/am-as/ets-am-as-bsxets.xml
Corresponding issue: [#710](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/710)
=> am-as-a.2 missingElement and missingAttribute property fixed

data-ac-mf/ac-mf-ia/ets-ac-mf-ia-bsxets.xml, data-am/am-ia/ets-am-ia-bsxets.xml, data-br/br-ia/ets-br-ia-bsxets.xml, data-bu/bu-ia/ets-bu-ia-bsxets.xml, data-ef/ef-ia/ets-ef-ia-bsxets.xml, data-el/el-ia/ets-el-ia-bsxets.xml, data-er/er-ia/ets-er-ia-bsxets.xml, data-ge/ge-ia/ets-ge-ia-bsxets.xml, data-hb/hb-as/ets-hb-as-bsxets.xml, data-hb/hb-ia/ets-hb-ia-bsxets.xml, data-hh/hh-as/ets-hh-as-bsxets.xml, data-hh/hh-ia/ets-hh-ia-bsxets.xml, data-lc/lc-ia/ets-lc-ia-bsxets.xml, data-lu/lu-ia/ets-lu-ia-bsxets.xml, data-mr/mr-ia/ets-mr-ia-bsxets.xml, data-nz/nz-ia/ets-nz-ia-bsxets.xml, data-of/of-ia/ets-of-ia-bsxets.xml, data-pd/pd-ia/ets-pd-ia-bsxets.xml, data-pf/pf-ia/ets-pf-ia-bsxets.xml, data-ps/ps-ia/ets-ps-ia-bsxets.xml, data-sd/sd-ia/ets-sd-ia-bsxets.xml, data-so/so-ia/ets-so-ia-bsxets.xml, data-sr/sr-ia/ets-sr-ia-bsxets.xml, data-su/su-ia/ets-su-ia-bsxets.xml, data-us/us-ia/ets-us-ia-bsxets.xml
Corresponding issue: [#963](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/963)
=> API call added to IA and AS themes 

data-lc/lc-ia/ets-lc-ia-bsxets.xml
Corresponding issue: [#1050](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1050)
=> lc-ia.b.2 added

service/ds-atom-pre-defined-soapui-project.xml
Corresponding issue: [#1143](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1143)
=> Predefined ATOM source links changed to master

service/dis-csw-core-soapui-project.xml, service/ds-sos-pre-defined-soapui-project.xml, service/vs-wms-soapui-project.xml, service/vs-wmts-soapui-project.xml
Corresponding issue: [#558](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/558)
=> HTTP response headers in services are case insensitive

service/dis-csw-core-soapui-project.xml, service/ds-sos-pre-defined-soapui-project.xml, service/vs-wmts-soapui-project.xml
Corresponding issue: [#1217](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1217)
=> CSW, SOS and WMTS getCaseInsensitive undone

service/vs-wms-soapui-project.xml
Corresponding issue: [#1208](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1208)
=> WMS at47 and at68 GetCaseInsensitive undone
